version: '3'
services:
  sqs:
    image: vsouza/sqs-local
    ports:
      - 9324:9324
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=q1w2e3
      - http.port=9200
      - http.cors.allow-origin=*
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  dejavu:
    image: appbaseio/dejavu
    depends_on:
      - elasticsearch
    ports:
      - 1358:1358
  db:
    image: postgres 
    restart: always
    environment:
      - POSTGRES_PASSWORD=mypass
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080